name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk python3-pip \
            autoconf automake libtool pkg-config zlib1g-dev cmake \
            libffi-dev libssl-dev m4 libncurses5-dev libncursesw5-dev \
            libtinfo6 libncurses6 help2man libltdl-dev

      - name: Fix Autoconf Macros
        run: |
          sudo cp /usr/share/aclocal/libtool.m4 /usr/share/autoconf/autoconf/ || true

      - name: Install Build Tools
        run: |
          python -m pip install --upgrade pip
          pip install buildozer cython==0.29.33 setuptools

      - name: Build with Buildozer
        run: |
          unset ANDROID_NDK_HOME
          unset ANDROID_NDK_ROOT
          export ANDROID_NDK_HOME=""
          export ANDROID_NDK_ROOT=""
          yes | buildozer android debug
        continue-on-error: false

      - name: Upload APK (All-Scan Mode)
        uses: actions/upload-artifact@v4
        with:
          name: BilgiYarismasi-APK
          # 'bin/*.apk' yerine bu kalıp tüm alt klasörleri tarar ve dosyayı yakalar
          path: "**/*.apk"
          retention-days: 5
